export const CATEGORIES = [
  { id: "commercial", name: "Commercial" },
  { id: "interior", name: "Interior" },
  { id: "architecture", name: "Architecture" },
  { id: "residential", name: "Residential" },
];

export const PROJECTS = [
  {
    id: 1,
    title: "BAT BD Farmer Waiting Station & Training Center",
    category: "Institutional",
    categoryId: "institutional",
    location: "MLD, Kushtia",
    thumbnail: "/images/bat-kushtia-night.jpg",
    description:
      "A community facility rooted in the Bangladeshi courtyard tradition, with tobacco-leaf-inspired facade screens and warm material honesty.",
    longDescription:
      "Designed for British American Tobacco Bangladesh at their leaf district in Kushtia, this facility serves as a waiting and training hub for tobacco farmers. The design draws from the traditional Bangladeshi courtyard (uthan) — a shared outdoor heart that organises the programme around a central green court. The facade is articulated with metal screens abstracting the form of tobacco leaves, lending the building a site-specific identity rooted in its agricultural context. Brick, timber, and steel are used in their honest expression, giving the project warmth and permanence.",
    client: "BAT Bangladesh",
    architect: "Archeground Ltd",
    type: "Institutional",
    concept: "Courtyard + Tobacco Leaf Facade",
    year: "2024",
    galleryLabels: [
      "View from Entry Gate",
      "Front Elevation",
      "Courtyard",
      "Lounge Interior",
      "Night View",
    ],
    gallery: [
      "/images/bat-kushtia-exterior.jpg",
      "/images/bat-kushtia-elevation.jpg",
      "/images/bat-kushtia-courtyard.jpg",
      "/images/bat-kushtia-lounge.jpg",
      "/images/bat-kushtia-night.jpg",
    ],
  },
  {
    id: 2,
    title: "Faculty of Earth Sciences & Engineering, University of Dhaka",
    category: "Institutional",
    categoryId: "institutional",
    location: "University of Dhaka",
    thumbnail: "/images/du-dean-room.jpg",
    description:
      "A comprehensive interior design for the Faculty of Earth & Environmental Science and Engineering & Technology Building — warm timber tones and refined detailing for academic excellence.",
    longDescription:
      "Commissioned by the University of Dhaka, this project covers 15,650 SFT across multiple faculty spaces including the Dean's Office, Waiting Area, Officer's Rooms, Conference Room, and Meeting Room. The design draws on a restrained material palette of warm oak veneer, off-white plaster, and dark metal accents — creating an atmosphere of scholarly authority balanced with contemporary clarity. Slatted ceiling elements and layered lighting give each room a distinct spatial identity while maintaining cohesion across the floor.",
    client: "University of Dhaka",
    architect: "arch INNER",
    type: "Institutional Interior",
    concept: "Academic Space — Earth Sciences Faculty",
    year: "2024",
    galleryAspectRatio: "4/3",
    galleryLabels: [
      "Dean's Room",
      "Dean's Room — View 2",
      "Dean's Waiting Area",
      "Officer's Room",
      "Conference Room",
    ],
    gallery: [
      "/images/du-dean-room.jpg",
      "/images/du-dean-room-2.jpg",
      "/images/du-waiting.jpg",
      "/images/du-officers.jpg",
      "/images/du-conference.jpg",
    ],
  },
  {
    id: 3,
    title: "Fervent Multiboard Industries — Chairman Floor",
    category: "Commercial",
    categoryId: "commercial",
    location: "Mohakhali C/A, Dhaka",
    thumbnail: "/images/fervent-reception.jpg",
    description:
      "An executive interior for a prominent industrial conglomerate — structured opulence expressed through bespoke millwork, curated stone finishes, and precision lighting.",
    longDescription:
      "The Chairman Floor of Fervent Multiboard Industries Ltd. spans a full executive level in Mohakhali, Dhaka. The brief called for a workplace that projects authority and refinement — a setting worthy of boardroom-level decision-making. The reception greets visitors with the company identity embedded in a dramatic slatted wood backdrop and warm chandelier. The Chairman's Room features a circular feature ceiling with ambient coffers, full-height joinery, and a panoramic city outlook. Supporting spaces — the lounge, director's room, and private dining — carry the same language: rich veneers, muted stone, and measured luxury.",
    client: "Fervent Multiboard Industries Ltd.",
    architect: "arch INNER",
    type: "Commercial Interior",
    concept: "Executive Chairman Floor",
    year: "2025",
    galleryAspectRatio: "4/3",
    galleryLabels: [
      "Reception Area",
      "Lobby Corridor",
      "Chairman's Room",
      "Chairman's Lounge",
      "Dining Area",
    ],
    gallery: [
      "/images/fervent-reception.jpg",
      "/images/fervent-lobby.jpg",
      "/images/fervent-chairman.jpg",
      "/images/fervent-lounge.jpg",
      "/images/fervent-dining.jpg",
    ],
  },
  {
    id: 5,
    title: "Dhaka Bank PLC — Kalatia Branch",
    category: "Commercial",
    categoryId: "commercial",
    location: "Kalatia, Keraniganj, Dhaka",
    thumbnail: "/images/dhaka-bank-lounge.jpg",
    description:
      "A full-branch interior for Dhaka Bank PLC at Kalatia — a calm, trust-inspiring banking environment built around warm wood tones, acoustic comfort, and clear spatial zoning for customers and staff.",
    longDescription:
      "Commissioned by Dhaka Bank PLC for their Kalatia Branch, this interior project covers the complete fit-out of a modern retail bank. The design is guided by the bank's brand ethos — 'Your Trust. Our Commitment.' — translated into a material palette of warm oak veneer, grey stone-finish tiles, and cream texture walls that communicate reliability without formality. The open banking floor is organised around a central teller counter with perforated timber cladding and under-counter lighting, flanked by a customer waiting lounge featuring blue upholstered seating beneath circular ring pendant lights. Glass-partitioned officer rooms and a dedicated meeting room maintain visual openness while providing acoustic separation. Wall graphics carrying the bank's vision, mission, and brand identity are integrated as spatial elements rather than afterthoughts. Floor finishes include Flotex carpet in the waiting zone and vinyl and ceramic tiles in the transactional areas — each zone coded by material.",
    client: "Dhaka Bank PLC",
    architect: "arch INNER",
    type: "Commercial Interior",
    concept: "Banking Excellence — Trust · Clarity · Warmth",
    year: "2026",
    galleryAspectRatio: "4/3",
    galleryLabels: [
      "Customer Waiting Lounge",
      "Banking Floor — Overview",
      "Teller Counter Zone",
      "Manager's Room",
      "Reception Counter",
    ],
    gallery: [
      "/images/dhaka-bank-lounge.jpg",
      "/images/dhaka-bank-floor-1.jpg",
      "/images/dhaka-bank-floor-2.jpg",
      "/images/dhaka-bank-manager.jpg",
      "/images/dhaka-bank-reception.jpg",
    ],
  },
  {
    id: 4,
    title: "Servisol ITES — Office Interior",
    category: "Commercial",
    categoryId: "commercial",
    location: "Bhai Bhai Plaza, Khilkhet, Dhaka-1229",
    thumbnail: "/images/servisol-reception.jpg",
    description:
      "A vibrant IT-enabled services office where bold colour zoning, acoustic panels, and open workstation planning create an energising environment for a growing tech workforce.",
    longDescription:
      "Covering 4,752 SFT across the second floor of Bhai Bhai Plaza, this office interior for Servisol ITES rejects corporate monotony in favour of dynamic energy. The reception makes an immediate brand statement — the SERVISOL ITES logo is set against a bold colour-block wall beneath a signature circular coved ceiling, framed by colourful modular seating. Director suites behind glass partitions feature geometric timber feature walls in warm oak, offering acoustic separation without visual heaviness. The sprawling workstation floor is planned for high-density IT operations: low-partition bays, integrated cable management, and an ever-present tech-themed mural that reinforces company identity. Material palette — flotex carpet, acoustic timber slats, fabric panels, and texture paint — is tuned to absorb noise and sustain long work hours.",
    client: "Servisol ITES",
    architect: "arch INNER",
    type: "Commercial Interior",
    concept: "Tech Office — Vibrant Collaborative Workspace",
    year: "2025",
    galleryAspectRatio: "4/3",
    galleryLabels: [
      "Reception & Waiting Area",
      "Director's Waiting Lounge",
      "Director's Room",
      "Workstation Zone",
      "Meeting Room",
    ],
    gallery: [
      "/images/servisol-reception.jpg",
      "/images/servisol-waiting.jpg",
      "/images/servisol-director-room.jpg",
      "/images/servisol-workstation.jpg",
      "/images/servisol-meeting.jpg",
    ],
  },
];
